# Generated by Django 5.2.1 on 2025-05-25 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackStorage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='created_at',
        ),
    ]
