# Generated by Django 5.2.1 on 2025-05-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackStorage', '0002_remove_trip_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='endPlaceType',
            new_name='end_place_type',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='financialSituation',
            new_name='financial_situation',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='socialStatus',
            new_name='social_status',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='startPlaceType',
            new_name='start_place_type',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='transportationCosts',
            new_name='transportation_costs',
        ),
    ]
