# Generated by Django 5.2.1 on 2025-05-25 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackStorage', '0003_rename_endplacetype_trip_end_place_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='end_place_type',
            new_name='endplacetype',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='financial_situation',
            new_name='financialsituation',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='social_status',
            new_name='socialstatus',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='start_place_type',
            new_name='startplacetype',
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='transportation_costs',
            new_name='transportationcosts',
        ),
    ]
