# Generated by Django 5.2.1 on 2025-05-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackStorage', '0004_rename_end_place_type_trip_endplacetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='endplacetype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='startplacetype',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trip',
            name='transportationcosts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
