# Generated by Django 5.2.1 on 2025-05-25 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trackStorage', '0006_rename_accelerometermax_point_accelerometermax_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='point',
            old_name='gyroscopeUncalibratedmagnitudemax',
            new_name='gyroscopeuncalibratedmagnitudemax',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='gyroscopeUncalibratedmagnitudemean',
            new_name='gyroscopeuncalibratedmagnitudemean',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='gyroscopeUncalibratedmagnitudemin',
            new_name='gyroscopeuncalibratedmagnitudemin',
        ),
        migrations.RenameField(
            model_name='point',
            old_name='gyroscopeUncalibratedmagnitudestd',
            new_name='gyroscopeuncalibratedmagnitudestd',
        ),
    ]
